# Generated by Django 5.2.7 on 2025-11-01 15:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Appliance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('average_power_Kwh', models.FloatField()),
                ('average_duration', models.DurationField()),
            ],
            options={
                'verbose_name_plural': 'Appliances',
            },
        ),
        migrations.CreateModel(
            name='GreenHourPrediction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('predicted_start', models.DateTimeField()),
                ('predicted_end', models.DateTimeField()),
                ('renewable_percentage', models.FloatField()),
                ('confidence', models.FloatField(blank=True, null=True)),
            ],
            options={
                'verbose_name_plural': 'Green Hour Predictions',
            },
        ),
        migrations.CreateModel(
            name='ApplianceProperty',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('frequency_per_week', models.IntegerField()),
                ('earliest_start_time', models.TimeField()),
                ('latest_end_time', models.TimeField()),
                ('preferred_days', models.CharField(max_length=100)),
                ('preferred_start_time', models.TimeField()),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Appliance Properties',
            },
        ),
        migrations.CreateModel(
            name='EventInstance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_time', models.DateTimeField()),
                ('end_time', models.DateTimeField()),
                ('green_score', models.FloatField()),
                ('status', models.CharField(default='scheduled', max_length=50)),
                ('appliance', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='scheduler.appliance')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Event Instances',
            },
        ),
    ]
