# Generated by Django 5.2.7 on 2025-11-02 07:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CarbonPredictions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField()),
                ('carbon_intensity', models.FloatField()),
            ],
            options={
                'verbose_name_plural': 'Carbon Predictions',
            },
        ),
        migrations.DeleteModel(
            name='GreenHourPrediction',
        ),
    ]
