# Generated by Django 5.2.7 on 2025-11-02 11:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0002_carbonpredictions_delete_greenhourprediction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='eventinstance',
            name='end_time',
        ),
        migrations.RemoveField(
            model_name='eventinstance',
            name='green_score',
        ),
        migrations.RemoveField(
            model_name='eventinstance',
            name='status',
        ),
    ]
