# Generated by Django 5.2.7 on 2025-11-02 11:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('scheduler', '0003_remove_eventinstance_end_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eventinstance',
            name='appliance',
            field=models.CharField(max_length=100),
        ),
    ]
